"""IsolateGPT agent with Hub-Spoke architecture for tool isolation.

This module implements the core IsolateGPT graph with:
- Hub Node: Plans tasks, routes inter-spoke communication (ISC)
- Spoke Nodes: Per-app isolated execution
- Tool Node: Executes tools
"""

import uuid
from typing import Sequence
from langchain_core.messages import AIMessage, BaseMessage, ToolMessage, HumanMessage
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.graph.state import CompiledStateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt.tool_node import ToolNode
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.tools import render_text_description_and_args

from .prompts import HUB_PROMPT, HUB_OUTPUT_FORMAT, SPOKE_PROMPT
from .tool_manager import ToolManager
from .utils import bind_tools


def create_isolate_gpt_graph(
    llm,
    tools,
) -> CompiledStateGraph:
    """Create the IsolateGPT agent graph.

    Args:
        llm: The language model instance.
        tools: List of tools available to the agent.

    Returns:
        Compiled LangGraph state graph.
    """
    # Filter out _u tools (PFI-specific, not used in agentdojo)
    tools = [tool for tool in tools if not tool.name.endswith("_u")]

    class AgentState(TypedDict):
        plan: Sequence[dict]  # Plan generated by Hub
        current_spoke: str  # Current spoke_id ({app_id}_{session_id})
        messages: Sequence[BaseMessage]  # Message of current spoke
        saved_messages: dict  # Saved messages of app spokes
        isc_request: dict  # Most recent ISC request
        isc_response: dict  # Most recent ISC response
        spoke_call_stack: list  # Stack of spoke IDs waiting for ISC response
        warnings: list  # List of warnings (kept in state only)

    class Warning:
        def __init__(self, caller_app=None, callee_app=None, tool_name=None, tool_args=None):
            self.caller_app = caller_app
            self.callee_app = callee_app
            self.tool_name = tool_name
            self.tool_args = tool_args

        def to_dict(self):
            return {
                "caller_app": self.caller_app,
                "callee_app": self.callee_app,
                "tool_name": self.tool_name,
                "tool_args": self.tool_args
            }

    def filter_plan(plan):
        """Filter and group plan steps by dependencies."""
        tool_names = [tool.name for tool in tools]
        filtered_steps = [step for step in plan["steps"] if step["name"] in tool_names]
        output_key_to_step = {}
        grouped_steps = []

        for step in filtered_steps:
            # Determine if the step is dependent on a previous step
            dependent = False
            for input_key, input_value in step['input'].items():
                if isinstance(input_value, str) and input_value.startswith("<") and input_value.endswith(">"):
                    dependent_key = input_value[1:-1]
                    if dependent_key in output_key_to_step:
                        dependent = True
                        grouped_steps[output_key_to_step[dependent_key]].append(step)
                        break

            # If the step is not dependent on any previous step's output, start a new group
            if not dependent:
                grouped_steps.append([step])

            # Record the output key of this step
            if 'output' in step:
                output_key_to_step[step['output']] = len(grouped_steps) - 1

        return grouped_steps

    def hub_node(state):
        """Hub node: plans tasks, routes ISC, detects unauthorized access."""
        if state.get("isc_request"):  # ISC request
            state.setdefault("spoke_call_stack", []).append(state["isc_request"]["spoke_id"])

            startup_app_id = tool_manager.get_app_id_from_tool(state["isc_request"]["functionality_request"])

            # Check if the app was planned
            app_planned = False
            for grouped_steps in state["plan"]:
                for step in grouped_steps:
                    step_app_id = tool_manager.get_app_id_from_tool(step["name"])
                    if step_app_id == startup_app_id:
                        app_planned = True
                        break

            # If the app was not planned, generate a warning (kept in state only)
            if not app_planned:
                new_warning = Warning(
                    caller_app=tool_manager.get_apps()[int(state["current_spoke"].split("_")[0]) - 1],
                    callee_app=tool_manager.get_app_from_tool(state["isc_request"]["functionality_request"]),
                    tool_name=state["isc_request"]["functionality_request"],
                    tool_args=state["isc_request"]["request_body"]
                )
                state.setdefault("warnings", []).append(new_warning)

            session_id = uuid.uuid4()
            spoke_id = f"{startup_app_id}_{session_id}"

            state["current_spoke"] = spoke_id

            return state
        elif state.get("isc_response"):  # ISC response
            # Deliver response to corresponding spoke
            state["current_spoke"] = state["spoke_call_stack"].pop()
            return state
        elif state.get("current_spoke") is None:  # User request
            # If one shot example is given, generate plan with final user query only
            example_given = len(state["messages"]) > 1
            if example_given:
                query_with_example = state["messages"]
                state["messages"] = state["messages"][-1:]

            # Generate plan using llm
            plan = hub_agent.invoke({"messages": state["messages"]})
            filtered_plan = filter_plan(plan)
            num_step_list = len(filtered_plan)
            state["plan"] = filtered_plan

            if num_step_list == 0:
                raise ValueError("No tools found in the plan")
            elif num_step_list == 1:
                # Start corresponding app spoke node
                startup_app_id = tool_manager.get_app_id_from_tool(filtered_plan[0][0]['name'])
            else:
                # Start routing spoke node
                startup_app_id = "0"
            session_id = uuid.uuid4()
            spoke_id = f"{startup_app_id}_{session_id}"
            state["current_spoke"] = spoke_id

            if example_given:
                state["messages"] = query_with_example

            return state
        else:
            # Final answer
            return state

    def spoke_node(state):
        """Spoke node: per-app isolated execution."""
        # Get App ID & make a tool list for spoke agent
        app_id = state["current_spoke"].split("_")[0]
        in_spoke_tools = tool_manager.get_tools_from_app_id(app_id)

        # Generate input for spoke agent
        if state.get("isc_request"):
            request = f"{state['isc_request']['functionality_request']}({state['isc_request']['request_body']})"
            state["messages"] = [HumanMessage(content=request)]
        elif state.get("isc_response"):
            response = state["isc_response"]["response"]
            spoke_id = state["current_spoke"]
            state["messages"] = state["saved_messages"][spoke_id]
            tool_call = state["messages"][-1].tool_calls[0]
            state["messages"] = add_messages(state["messages"], [ToolMessage(content=response, tool_call_id=tool_call["id"], name=tool_call["name"])])
        else:  # User request or tool message
            pass  # No need to change state

        # Invoke LLM & return output tool call or final answer
        result = spoke_agent.invoke({"messages": state["messages"]})
        result = AIMessage(**result.dict(exclude={"type", "name", "additional_kwargs"}))
        has_tool_calls = isinstance(result, AIMessage) and result.tool_calls

        if has_tool_calls:
            # Check if tool call is for current app
            tool_call = result.tool_calls[0]
            if tool_call["name"] in in_spoke_tools:
                # Execute tool directly without sending ISC request
                state["messages"] = add_messages(state["messages"], [result])
                state["isc_request"] = None
                state["isc_response"] = None

                return state
            else:
                # Send ISC request to hub
                state["messages"] = add_messages(state["messages"], [result])
                state.setdefault("saved_messages", {})
                state["saved_messages"][state["current_spoke"]] = state["messages"]
                state["messages"] = []
                state["isc_request"] = {
                    "spoke_id": state["current_spoke"],
                    "functionality_request": tool_call["name"],
                    "request_body": tool_call["args"]
                }
                state["isc_response"] = None
                return state
        else:
            state["messages"] = add_messages(state["messages"], [result])
            state.setdefault("saved_messages", {})
            state["saved_messages"][state["current_spoke"]] = state["messages"]
            state["isc_request"] = None

            if len(state.get("spoke_call_stack", [])) == 0:
                # Send final answer to hub
                state["isc_response"] = None
                return state
            else:
                # Send isc response to hub
                state["isc_response"] = {
                    "spoke_id": state["current_spoke"],
                    "response": result.content
                }
                return state

    def tool_node_wrapper(state: AgentState) -> AgentState:
        """Tool node: executes tools and handles results."""
        tool_node = ToolNode(tools, handle_tool_errors=True)

        # Remove all tool calls except the first one (Parallel tool calls are disabled)
        for message in reversed(state["messages"]):
            if message.type == "ai":
                ai_tool_call = message
                break
        ai_tool_call.tool_calls = ai_tool_call.tool_calls[:1]
        tool_res = tool_node.invoke(state)

        # Use standard tool output directly (no PFI deserialization)
        state["messages"] = add_messages(state["messages"], tool_res["messages"])

        return state

    def create_hub_agent():
        """Create the hub agent for planning."""
        tool_info = render_text_description_and_args(tools)
        hub_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", HUB_PROMPT),
                MessagesPlaceholder(variable_name="messages"),
            ]
        )
        hub_prompt = hub_prompt.partial(output_format=HUB_OUTPUT_FORMAT, tools=tool_info)
        json_parser = JsonOutputParser()
        return hub_prompt | llm | json_parser

    def create_spoke_agent():
        """Create the spoke agent for tool execution."""
        spoke_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", SPOKE_PROMPT),
                MessagesPlaceholder(variable_name="messages"),
            ]
        )

        tool_binded_llm = bind_tools(llm, tools, enable_parallel_tool_calls=False, tool_call_only=False)

        return spoke_prompt | tool_binded_llm

    # Create agents and tool manager
    hub_agent = create_hub_agent()
    spoke_agent = create_spoke_agent()
    tool_manager = ToolManager(tools)

    # Define the graph
    workflow = StateGraph(AgentState)
    workflow.add_node("hub_node", hub_node)
    workflow.add_node("spoke_node", spoke_node)
    workflow.add_node("tool_node", tool_node_wrapper)

    workflow.set_entry_point("hub_node")

    def hub_node_router(state):
        """Route from hub node to spoke node or end."""
        if state.get("isc_request") or state.get("isc_response") or isinstance(state["messages"][-1], (HumanMessage, ToolMessage)):
            return "spoke_node"
        else:
            return "__end__"

    def spoke_node_router(state):
        """Route from spoke node to hub, tool, or end."""
        if state.get("isc_request") or state.get("isc_response"):
            return "hub_node"  # Send isc request / response to hub

        has_tool_calls = isinstance(state["messages"][-1], AIMessage) and state["messages"][-1].tool_calls
        if has_tool_calls:
            return "tool_node"  # Execute tool directly
        else:
            return "hub_node"  # Send final answer to hub

    workflow.add_edge(START, "hub_node")

    workflow.add_conditional_edges(
        "hub_node",
        hub_node_router,
        {
            "spoke_node": "spoke_node",
            "__end__": END
        }
    )

    workflow.add_conditional_edges(
        "spoke_node",
        spoke_node_router,
        {
            "hub_node": "hub_node",
            "tool_node": "tool_node"
        }
    )

    workflow.add_edge("tool_node", "spoke_node")

    return workflow.compile()
